### ISSUE TITLE
Add support for cmd+[ and cmd+]

### ISSUE THREAD

**Issue by fregante** [fregante/indent-textarea#3]
> Could you please add support for <kbd>cmd</kbd> + <kbd>[</kbd> and <kbd>cmd</kbd> + <kbd>]</kbd> too?
> _Originally posted by @vladimyr in https://github.com/bfred-it/indent-textarea/issues/1#issuecomment-473097559_

<kbd>cmd</kbd> + <kbd>[</kbd> works like the regular tab on multiple lines, but on a single line it indents the whole line, instead of adding a `\t` at the cursor position.

I actually had implemented this single-line behavior before but it was rejected because it wasn't the regular <kbd>tab</kbd> behavior: [sindresorhus/refined-github#567@`a9b91e3`](https://github.com/sindresorhus/refined-github/pull/567/commits/a9b91e309fde859862918032cd3fa4934caf5b15)

**Comment by bfred-it** [comment]
<kbd>cmd</kbd> + <kbd>[</kbd> works like the regular tab on multiple lines, but on a single line it indents the whole line, instead of adding a `\t` at the cursor position.

I actually had implemented this single-line behavior before but it was rejected because it wasn't the regular <kbd>tab</kbd> behavior: [sindresorhus/refined-github#567@`a9b91e3`](https://github.com/sindresorhus/refined-github/pull/567/commits/a9b91e309fde859862918032cd3fa4934caf5b15)
